### ISSUE TITLE
[11.0][muk_bundles_quality] Missing dependencies

### ISSUE THREAD

**Issue by SalahAdDin** [muk-it/muk_bundles#1]
Hello,

In the manifiest says:
```python
        "muk_quality_docs",
        "muk_quality_docs_dms",
        "muk_quality_docs_dms_converter",
        "muk_quality_docs_esc",
        "muk_quality_docs_mandatory",
        "muk_quality_docs_star",
        "muk_quality_docs_versioning",
```

But in [its](https://github.com/muk-it/muk_quality) repository you can see:
```
muk_quality_docs	update	5 hours ago
muk_quality_docs_dms	muk_quality_docs_dms	22 hours ago
muk_quality_docs_hr	QMS Release	3 days ago
```

**Comment by keshrath** [comment]
Hello, no, this is not an error. The basic QMS including the connection to our DMS is open source and can be downloaded either via Github or the Odoo Store. Some extensions are paid modules, which are therefore not in the public Github. However, the basic QMS is complete and usable as it is. The extensions bring only some additional functions and can be purchased individually or all at once with this bundle.

Link: https://apps.odoo.com/apps/modules/11.0/muk_bundle_quality_docs/
